version: "3.9"

services:
  loccar-locadora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loccar-locadora
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5433;Database=loccardb_locadora;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-locadora
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
