version: "3.9"

services:
  loccar-locadora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loccar-locadora
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=loccar-db;Port=5432;Database=loccardb;Username=postgres;Password=postgres;Pooling=true;
      - Jwt__Issuer=http://localhost
      - Jwt__Audience=http://localhost
      - Jwt__Key=7c83ca9b462e5932a0c506fee8cec2ac38edef8c1fec346c0eeb8471ad7bf84d
